name: Provider request
description: Suggest a new provider or improvement
title: ""
labels: ["request"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the feature
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Explain the idea
